language: java
sudo: false
jdk:
  - oraclejdk8
script:
  - mvn clean
  - cd dubbo-spring-boot-starter && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
  - cd spring-boot-starter-parent && mvn install -DskipTests=true -Dmaven.javadoc.skip=true
